#!/usr/local/bin/perl 
###################################################################################################
# NAME  : batch_touch_mtr.pl 
# TYPE  : perl
# OUTPUT: shows the real time batch touch status. 
#
#
# Usage:                #batch_touch_mtr.pl   30  all
#                          '30' :  to show the jobs delayed by 30 mins, set to '0' if empty.
#                          'all' :  to give all the complete/uncomplete jobs which were delayed, show only uncomplete jobs if empty.
#
# Date              Ver#         Modified By             Comments
# ----------        -----       ------------          ------------------------
# 2008-5-30          1.0         Kevin                   Initial Version
#
#                     Hist_avg file locates at /export/home/dx_wang/kevin/batch/dat/"$SUBJECT_AREA"_touch_hist.dat,
#                     generated by /export/home/dx_wang/kevin/batch/bin/sla_hist_avg_gen.pl everyday.
####################################################################################################

use strict;

my $Weekday=(localtime(time()))[6];
my $now=sprintf "%02d:%02d",(localtime(time()))[2,1,0];
my ($SUBJECT_AREA,$delay,$select)=(defined @ARGV)?@ARGV:();    #How many mins delay is allowed?  default delay set to 10mins
my $slash="="x100;
my $slaover=0;

##################################################################
#                     part 1   Definition
##################################################################

#define the past 10days.
my @day; 
foreach(@day=(0..9)){
    my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst)=localtime(time()-86400*$_);     
    $_=sprintf "%4d%02d%02d",$year+1900,$mon+1,$mday;
}

#minus function
sub minus {
    my ($bigger,$little)=@_;
    my $total=substr($bigger,0,2)*60+substr($bigger,3,2)-substr($little,0,2)*60-substr($little,3,2);
    return $total;
    }
    
# env setting    
my $pwd=`pwd`;
chomp $pwd;
my $HOME="/export/home/dx_wang/kevin/batch";
my $LOGDIR="$HOME/log";
my $ARCDIR="$HOME/arc";
my $TMPDIR="$HOME/tmp";
my $CFGDIR="$HOME/cfg";
my $DATDIR="$HOME/dat";
my $TOUCH_LIST_CFG="$CFGDIR/$SUBJECT_AREA"."_touch.cfg";
my $HIST_AVG_DAT="$DATDIR/$SUBJECT_AREA"."_touch_hist.dat";
my $COMP_CHECK_FILE="$TMPDIR/$SUBJECT_AREA"."_comp_check.$day[0]";
my $DELAYED_DAY_LIST="$DATDIR/$SUBJECT_AREA"."_delay_days.lis";
my $CORE_TOUCH_LIS="$DATDIR/$SUBJECT_AREA"."_core.lis";
my $MAIL_SEND_LIS="$DATDIR/$SUBJECT_AREA"."_mtr.tls";
my $usage="Usage:\t$pwd/touch_mtr.pl  $SUBJECT_AREA 30 all\n\t$SUBJECT_AREA  -> subject area:dw_sla,dw_kwdm...\n\t'30' ->to show the jobs delayed by 30 mins | default='0' if not given.\n\t'all' ->to give all complete/uncomplete jobs which were delayed | show only uncomplete jobs if not given.\n";
#my $info="*Hist_avg file locates at $HIST_AVG_DAT,\ngenerated by $pwd/sla_hist_avg_gen.pl everyday\n";

##################################################################
#                     part 2  Pre_check, Pre_process
##################################################################

# exit if $COMP_CHECK_FILE is already exist;
chdir $TMPDIR;
my @tmp=glob ("$SUBJECT_AREA"."_comp*$day[0]");
exit if(defined @tmp); 
# transfer the whole touch files list form oterh host
system("ls -tl /export/home/dw_adm/WatchFiles > $TMPDIR/pascal.wfl");
system("/usr/local/bin/ssh dx_wang\@liono.vip.ebay.com 'ls -tl /dw/etl/home/prod/watch/primary' > $TMPDIR/liono.wfl");
system("/usr/local/bin/ssh dx_wang\@sqwitetl03.smf.ebay.com 'ls -tl /dw/etl/home/prod/watch/primary' > $TMPDIR/etl03.wfl");

open(THFLL,"$TMPDIR/liono.wfl")|| die "can not open liono.wfl.$! \n";
my $TOUCH_L=do{local $/;<THFLL>;};
close(THFLL);
open(THFLP,"$TMPDIR/pascal.wfl")|| die "can not open pascal.wfl.$! \n";
my $TOUCH_P=do{local $/;<THFLP>;};
close(THFLP);
open(THFL03,"$TMPDIR/etl03.wfl")|| die "can not open etl03.wfl.$! \n";
my $TOUCH_03=do{local $/;<THFL03>;};
close(THFL03);
open(HISTDAT,"$HIST_AVG_DAT")||die "can not open $HIST_AVG_DAT.$! \n";
my $HISTDAT=do{local $/;<HISTDAT>;};
close(HISTDAT);


open(DAILYLOG,">$LOGDIR/$SUBJECT_AREA"."_touch_status.$day[0]")||die "can not write tmp file:$!";
close(DAILYLOG);
open(DELAYLIST,">$LOGDIR/$SUBJECT_AREA"."_delay_lst.$day[0]")||die "can not wirte file:$!";
print DELAYLIST "\nThe following jobs are $delay mins late than average.\n\n";
close(DELAYLIST);

my ($TH_FILE,$TH_HOST,$TH_SUBJECT_AREA,$TH_UCJOB,$TH_JOBP,$TH_CORE);
my ($finish,$hist,$record,$max,$mail,$limit);
my (@TH_FILE);
my (%TOUCH_FILE_LIST,%TH_UCJOB,%TH_SUBJECT_AREA,%TH_JOBP,%CORE_F);

open(MAILLIS,"$MAIL_SEND_LIS")||die "cannot oep $! \n";
	$mail=do {local $/;<MAILLIS>;};
close(MAILLIS);
open(CORETHL,"$CORE_TOUCH_LIS")||die " cannot open $! \n";
    $TH_CORE=do {local $/;<CORETHL>;};
close(CORETHL);

open(TOUCHCFG,$TOUCH_LIST_CFG)||die "cant open:$!";
    foreach(<TOUCHCFG>){
        chomp;
        ($TH_FILE,$TH_HOST,$TH_SUBJECT_AREA,$TH_UCJOB,$TH_JOBP)=split(' ',$_);
        push(@TH_FILE,$TH_FILE);

        $TH_SUBJECT_AREA{$TH_FILE}=$TH_SUBJECT_AREA;
        $TH_UCJOB{$TH_FILE}=$TH_UCJOB;
		$TH_JOBP{$TH_FILE}=$TH_JOBP;
        if($TH_HOST eq "liono.vip.ebay.com"){
            $TOUCH_FILE_LIST{$TH_FILE}=$TOUCH_L;
        }
        elsif($TH_HOST eq "pascal.vip.ebay.com"){
            $TOUCH_FILE_LIST{$TH_FILE}=$TOUCH_P;
        }
        elsif($TH_HOST eq "sqwitetl03.smf.ebay.com"){
            $TOUCH_FILE_LIST{$TH_FILE}=$TOUCH_03;
        }
        else{
            warn"***Please check the host name for $TH_FILE!\n";
        }
        
    }
close(TOUCHCFG);

##################################################################
#                     part 3  start checking
##################################################################
open(DAILYLOG,">>$LOGDIR/$SUBJECT_AREA"."_touch_status.$day[0]")||die "can not write tmp file:$!";
open(DELAYLIST,">>$LOGDIR/$SUBJECT_AREA"."_delay_lst.$day[0]")||die "can not wirte file:$!";
printf DELAYLIST "%-10s%-10s%-50s%-30s\n$slash\n",'Status','Avg','UC4_job_names','UC4_jobplan';

    foreach(@TH_FILE){
		$hist=$1 if($HISTDAT=~/(..:..)     $_/);
	    if($TOUCH_FILE_LIST{$_}=~/(..:..) $_/){
            $finish=$1;
			#if it's Friday, ajust the complete time by 1h.
		    if($Weekday==5){ 
		        $finish=sprintf "%02d:%02d",substr($finish,1,2)-1,substr($finish,3,2);
		    }
			printf DAILYLOG "%-10s%-60s\n",$finish,$_;
			
			if($select eq 'all' and minus($finish,$hist)>$delay){
			    printf DELAYLIST "%-10s%-10s%-50s%-30s\n",$finish,$hist,$TH_UCJOB{$_},$TH_JOBP{$_};
				$record++;
		    }	
			# find out the maxtime,  in other words, SLA finish time
			if(minus($finish,$max)>0){
			    $max=$finish;
			}
			# log the core subject finish time
			if($TH_CORE=~/$_/){
			    $CORE_F{$_}=$finish;
			}
        }    
        else{
			$finish="N";
			$slaover=1;
			if($Weekday==5){
			    $delay+=60;
			}
			if(minus($now,$hist)>$delay){
		        printf DELAYLIST "%-10s%-10s%-50s%-30s\n",$finish,$hist,$TH_UCJOB{$_},$TH_JOBP{$_};
			    $record++;
		    }	
		}
    }
close(DAILYLOG);
##################################################################
#                     part 4  Post touch&output
##################################################################	
# IF SLA has finished
if($slaover==0){
#touch SLA complete file 
    open(COMPCHECK,">>$COMP_CHECK_FILE")||die "cannot write file:$!\n";  
	print COMPCHECK $slash,"\n";
	print COMPCHECK "SLA has finished at $max.\n\n";
	foreach $TH_FILE (keys %CORE_F){
	    printf COMPCHECK "%-10s%-20s%-40s\n",$CORE_F{$TH_FILE},$TH_SUBJECT_AREA{$TH_FILE},$TH_FILE;
	}
	print COMPCHECK $slash,"\n";
	close(COMPCHECK);
	open(COMPCHECK,"$COMP_CHECK_FILE")||die "cannot open file:$!\n";  
	print <COMPCHECK>;
	close(COMPCHECK);
	system("cat $COMP_CHECK_FILE | mailx -s '[SLA Monitor]: Jobs Finished \@ $max.' $mail");
# record the day if the SLA complete time is too late;
	open(EXDAYLIS,">>$DELAYED_DAY_LIST")||die "cannot write file:$!\n";
	print EXDAYLIS $day[0] if(minus($max,$limit)>0);  
	close(EXDAYLIS) ;
#generate the hist-avg time list
	system("/export/home/dx_wang/kevin/batch/bin/hist_avg_gen.pl $SUBJECT_AREA");
	exit;
}
# Else move on 
if($Weekday==5){
    print DELAYLIST "\* All Friday statistics have been ajusted by 1h.\n";
}   
print DELAYLIST "\n$slash\n$usage";
close(DELAYLIST);
open(DELAYLIST,"$LOGDIR/$SUBJECT_AREA"."_delay_lst.$day[0]")||die "cannot open file $!";
print <DELAYLIST>;
close(DELAYLIST);

if($record >=1){
system("cat $LOGDIR/$SUBJECT_AREA"."_delay_lst.$day[0] | mailx -s '[$SUBJECT_AREA Monitor]: Jobs delayed.' $mail");
}        
chdir $TMPDIR;
unlink("$SUBJECT_AREA"."_comp_check.$day[1]");
###########################End of program############################	