USE [Foodunion]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dm].[Dim_Store_Flg](
	[Store_ID] [varchar](50) NOT NULL,
	[Account_Store_Code] [varchar](50) NOT NULL,
	[FIRST_SALES_DATE_AMBIENT] [nvarchar](200) NULL,
	[FIRST_SALES_DATE_Fresh] [nvarchar](200) NULL,
	[Load_DTM] [datetime] NULL,
	[FIRST_SALES_DATE] [nvarchar](200) NULL,
	[FIRST_SALES_DATE_BOTH] [nvarchar](200) NULL,
 CONSTRAINT [PK_Dim_Store_Flg] PRIMARY KEY CLUSTERED 
(
	[Store_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
