USE [Foodunion]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dm].[Dim_indicator_desc](
	[Indicator] [nvarchar](50) NOT NULL,
	[Desc_CN] [nvarchar](500) NULL,
	[Report_NM] [nvarchar](50) NULL,
 CONSTRAINT [PK_Dim_indicator_desc] PRIMARY KEY CLUSTERED 
(
	[Indicator] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
